### ISSUE TITLE
Stringtable crash

### ISSUE THREAD

**Issue by Yogpod** [danielga/gm_sourcenet#53] opened 2021-12-19 21:07 UTC
When a client joins, they're met with this almost immediately 
![image](https://user-images.githubusercontent.com/22012249/146690631-620e8af7-b0ff-4d11-8cdf-03b92fd83635.png)

Checked what svc_CreateStringTable was doing, so I printed it
![image](https://user-images.githubusercontent.com/22012249/146690821-cbc946a7-028a-4181-8436-253c2e92f7d5.png)

This _is_ the x86-64 branch though so that may be part of the cause.

built w/ 
```
git clone --recursive -b x86-64-support-sourcesdk https://github.com/danielga/garrysmod_common.git
git clone --recursive -b update-lua-code https://github.com/danielga/gm_sourcenet.git
cd gm_sourcenet
gm_sourcenet$ ./premake5 --gmcommon=/home/yogpod/garrysmod_common gmake
gm_sourcenet$ cd projects/linux/gmake
gm_sourcenet/projects/linux/gmake$ make config=releasewithsymbols_x86_64 
```

I don't have gluapack or any other thing that would modify it & it doesn't happen if I don't load sourcenet

**Comment by danielga** [comment] 2021-12-19 21:52
How are you using sourcenet?

**Comment by danielga** [comment] 2021-12-19 21:59
A small reproducible sample would be appreciated.

**Comment by Yogpod** [comment] 2021-12-19 22:00
I'll give a sample when I get home in a few hours.

**Comment by Yogpod** [comment] 2021-12-20 07:22
Installed a new server from steamcmd, completely empty with just an addon that includes this file
https://pastebin.com/raw/7SbGwC9h

**Comment by danielga** [comment] 2021-12-20 14:14
Your script seems to cause that issue but if I use my branch AS IS, it works fine. As such, all I can tell you is treat that branch as WIP and anything can change at any time.

**Comment by danielga** [comment] 2021-12-20 14:16
The script I used to test that works properly (everything that is necessary is loaded by these):
```
include("sourcenet/incoming.lua")
include("sourcenet/outgoing.lua")
```
Inside `garrysmod/lua/sourcenet` are the support Lua scripts from this repository and branch.

**Comment by Yogpod** [comment] 2022-01-01 18:50
Tried this again with just the normal files in the same manner you tested with, still crashes in the same way. So I'd assume it's something with the x64 branch compiled version.

**Comment by danielga** [comment] 2022-01-01 18:52
Have you pulled the latest commit 4c6e1e488d8ab8be690ee7a21ec2ea6bae27f6d5?

**Comment by Yogpod** [comment] 2022-01-01 18:57
Yep, just tested again to make sure I did

**Comment by danielga** [comment] 2022-01-01 22:40
Okay, the problem wasn't the `x86-64` branch. The problem is something more obscure. In `outgoing.lua`, the `PreSendDatagram` hook copies each `bf_write` into a `bf_read` for parsing. It then parses each message and writes it into the original `bf_write`. Therein lies the problem. The code doesn't seek the original `bf_write` to the beginning, duplicating the contents. I am surprised that this issue doesn't happen on Windows SRCDS.

**Comment by danielga** [comment] 2022-01-01 22:41
I have pushed the fix to 50add426575ff55f5c495f83008d8c557348c238.

**Comment by Yogpod** [comment] 2022-01-01 22:42
Thanks! I'll try it out and tell you how it goes

**Comment by Yogpod** [comment] 2022-01-01 22:51
Issue still seems to be present after applying your fix

**Comment by danielga** [comment] 2022-01-01 22:57
I can't reproduce the issue anymore (on either `x86-64` or the main branch), so I can't help you further.

**Closed by danielga** 2022-01-01 22:57 UTC
Labels: bug

**Comment by Yogpod** [comment] 2022-01-15 18:40
Caused by some weird server issue, fixed it by just using a different server, apologies for the trouble
