### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by Dzhet225** [danielga/gm_sourcenet#6] opened 2018-01-06 18:26 UTC
Helo i use last version of precompiled gm_sourcenet.
if SERVER then
	AddCSLuaFile( "autorun/test.lua" )
	include( "sourcenet/server.lua" )
end
This crash my server with no warning.
http://dumps.metastruct.uk.to/dumper.py?dump=srcds_2117156_crash_2018_1_6T18_25_10C0.mdmp
https://imgur.com/OPDsn8j

**Comment by danielga** [comment] 2018-03-02 23:27
@Dzhet225 I am unable to reproduce, are you using the latest version?

**Comment by danielga** [comment] 2018-04-22 16:15
Unable to reproduce, closing.

**Closed by danielga** 2018-04-22 16:15 UTC
Labels: bug
